#!/bin/zsh
# Script to run watch network wit ss (it can watch a firejail network namespace) 
# Requires zsh

FIREJAIL_NS=""
SS_OPTS="-tuap --options"
WATCH_OPTS="-d -c -p -n 1"

while [[ $# > 0 ]]; do
    if [[ $1 =~ ^--firejail=(.+)$ ]]; then
        FIREJAIL_NS=$match
        shift
    elif [[ $1 =~ ^--ss-opts=(.+)$ ]]; then
        echo "$match"
        SS_OPTS="$match"
        shift
    elif [[ $1 =~ ^--watch-opts=(.+)$ ]]; then
        WATCH_OPTS=$match
        shift
    else
        echo "Usage: watch-ss options"
        echo ""
        echo "Options:"
        echo "   --firejail=namespace"
        echo "   --ss-opts=\"ss options\""
        echo "   --watch-opts=\"watch options\""
        echo
        exit 1
    fi
done

if [[ $FIREJAIL_NS != "" ]]; then
    firejail --join-network=$FIREJAIL_NS bash -c "watch ${WATCH_OPTS} /sbin/ss ${SS_OPTS}"
else
    watch ${WATCH_OPTS} /sbin/ss ${SS_OPTS}
fi
